import { ArrowLeft, ArrowRight, User, Briefcase, Gauge, ShieldCheck, CheckCircle2, FileText, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Props {
  onBack: () => void;
  onNext: () => void;
  data: Record<string, string>;
}

export const Report = ({ onBack, onNext, data }: Props) => {
  const sections = [
    {
      icon: User,
      title: "Customer Details",
      items: [
        ["Full Name", data.name || "Rohan Sharma"],
        ["Application ID", "KYC-2024-08821"],
        ["KYC Date", new Date().toLocaleDateString("en-IN")],
        ["PAN", "ABCDE1234F"],
      ],
    },
    {
      icon: Briefcase,
      title: "Financial Details",
      items: [
        ["Monthly Income", `₹${data.income || "85,000"}`],
        ["Employment", data.employment || "Salaried"],
        ["Loan Purpose", data.purpose || "Home Renovation"],
        ["Requested Amount", `₹${data.amount || "2,00,000"}`],
      ],
    },
    {
      icon: Gauge,
      title: "Credit Score",
      items: [
        ["Score", "782 / 900"],
        ["Bureau", "CIBIL"],
        ["Rating", "Excellent"],
        ["Past Defaults", "None"],
      ],
    },
    {
      icon: ShieldCheck,
      title: "Verification Status",
      items: [
        ["Video KYC", "✓ Passed"],
        ["Liveness Check", "✓ Passed"],
        ["Document OCR", "✓ Verified"],
        ["Face Match", "98.2%"],
      ],
    },
  ];

  return (
    <div className="w-full max-w-5xl mx-auto animate-fade-in">
      <div className="bg-card rounded-3xl shadow-card border border-border/60 overflow-hidden">
        <div className="bg-gradient-dark px-6 py-6 text-secondary-foreground flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-2xl bg-primary/20 flex items-center justify-center">
              <FileText className="w-6 h-6 text-primary" />
            </div>
            <div>
              <h2 className="text-xl font-bold">Loan Origination Report</h2>
              <p className="text-sm text-secondary-foreground/70">Generated by AI · {new Date().toLocaleString("en-IN")}</p>
            </div>
          </div>
          <div className="px-3 py-1.5 rounded-full bg-success/20 text-success text-xs font-semibold">
            DECISION: APPROVED
          </div>
        </div>

        <div className="p-6 grid md:grid-cols-2 gap-5">
          {sections.map((s) => (
            <div key={s.title} className="rounded-2xl border border-border/60 p-5 bg-muted/20">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-9 h-9 rounded-xl bg-accent text-accent-foreground flex items-center justify-center">
                  <s.icon className="w-4 h-4" />
                </div>
                <h3 className="font-semibold">{s.title}</h3>
              </div>
              <dl className="space-y-2.5">
                {s.items.map(([k, v]) => (
                  <div key={k} className="flex items-baseline justify-between gap-3 text-sm">
                    <dt className="text-muted-foreground">{k}</dt>
                    <dd className="font-medium text-right">{v}</dd>
                  </div>
                ))}
              </dl>
            </div>
          ))}
        </div>

        <div className="px-6 pb-6 space-y-5">
          <div className="rounded-2xl border border-success/30 bg-success/5 p-5">
            <div className="flex items-center gap-2 mb-3">
              <CheckCircle2 className="w-5 h-5 text-success" />
              <h3 className="font-semibold">Final Decision</h3>
            </div>
            <p className="text-sm">
              <span className="font-semibold text-success">Approved</span> for ₹2,00,000 at 10.5% p.a. for 60 months. EMI ₹4,292.
            </p>
          </div>

          <div className="rounded-2xl border border-border/60 p-5 bg-gradient-subtle">
            <div className="flex items-center gap-2 mb-3">
              <Sparkles className="w-5 h-5 text-primary" />
              <h3 className="font-semibold">AI Explanation</h3>
            </div>
            <p className="text-sm leading-relaxed text-muted-foreground">
              The applicant demonstrated strong identity verification (98.2% face match) and stable income patterns.
              CIBIL score of 782 indicates excellent creditworthiness. Voice and behavioral analysis during the video KYC
              showed high confidence with no signs of fraud or coercion. Debt-to-income ratio is well within safe thresholds,
              supporting a low-risk classification.
            </p>
          </div>
        </div>

        <div className="px-6 pb-6 flex flex-col sm:flex-row gap-3">
          <Button variant="outline" size="lg" className="sm:flex-1" onClick={onBack}>
            <ArrowLeft className="w-4 h-4" /> Back to Result
          </Button>
          <Button variant="hero" size="lg" className="sm:flex-1" onClick={onNext}>
            Proceed to Disbursement <ArrowRight className="w-4 h-4" />
          </Button>
        </div>
      </div>
    </div>
  );
};
